apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
    - { name: node1, address: 192.168.50.241, internalAddress: 192.168.50.241, user: putao, password: "123123" }
  roleGroups:
    etcd:
      - node1
    master:
      - node1
    worker:
      - node1
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    #internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: cilium
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: [ ]
    insecureRegistries: [ ]
  addons: [ ]


