version: '3.1'

services:
  gfw-master:
    image: harbor.putao282.com:2443/library/gfw_center:3.0.0
    restart: always
    ports:
      - 0.0.0.0:805:805
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime